import type { Ruleset } from "../../domain/src/types.js";

export const DEFAULT_RULESET: Ruleset = {
  version: "sim0.0.10",
  weeksPerYear: 52,
  markets: 20,
  promotions: 9,
  wrestlers: 400,
  initialContractedTalentRatio: 0.68,
  careerTimeFactor: 0.14,
  renewalWindowWeeks: 4,
  maxRecruitmentOffersPerPromotionPerWeek: 2,
  offerAcceptanceThreshold: 50,
  majorEventIntervalWeeks: 13,
  minEventParticipants: 6,
  injuryRateMultiplier: 1,
  fatigueRecoveryBase: 14,
  developmentRate: 1,
  retirementBaseAge: 42,
  talentGenerationFloorRatio: 0.96,
  maxProspectsGeneratedPerWeek: 2,
  survivalEvaluationIntervalWeeks: 4,
  survivalDistressThresholdWeeks: 8,
  survivalCrisisDormancyWeeks: 24,
  survivalUnderstaffedDormancyWeeks: 12,
  survivalRecoveryWeeks: 8,
  survivalMinimumRosterRatio: 0.35,
  survivalEmergencyRecruitmentPerCycle: 2,
  survivalRestructureIntervalWeeks: 12,
  teamRecognitionMatches: 20,
  singlesTitleDefenseIntervalWeeks: 8,
  tagTitleDefenseIntervalWeeks: 10,
};
